n = input('DIgite algo:')
t = type(n)
print('O tipo primitivo desse valor é: {}' .format(t)) 
print('Só tem espaços? {}'.format(n.isspace()))
print('É um número? {}' .format(n.isnumeric()))
print('É alfabético? {}' .format(n.isalpha()))
print('É alfanúmerico? {}' .format(n.isalnum()))
print('Está em maiucúlo? {}' .format(n.isupper()))
print('Está em minúsculo? {}' .format(n.islower()))
print('Está capitalizada? {}' .format(n.istitle()))